### ISSUE TITLE
License

### ISSUE THREAD

**Issue by tech189** [nad2000/memrise-scraper#1]
I just wanted to let you know that I have used your code to create a not very pretty but practical online version of your scraper here: http://tech189.duckdns.org/memrise/

I would like to check whether I have attributed you sufficiently.

Thanks!

**Comment by tech189** [comment]
No problem, I've added your real name.

**Comment by nad2000** [comment]
all good!

Radomirs Cirskis MCDBA, MCAD C#, MCSD .NET C#, ZCE PHP5, MCSD VB6 ...
M: +64 221 221 442 | E: RAD@nowITworks.eu <rad@nowitworks.eu>
[image: View my profile on LinkedIn] <http://nz.linkedin.com/in/nad2000>
